### ISSUE TITLE
2.0.13 (alpha 1 for MC1.7.9) not working in 1.7.10 server

### ISSUE THREAD

**Issue by DevinderFTW** [CitizensDev/Citizens2#838]
`[15:29:17] [Server thread/INFO] [net.citizensnpcs.Citizens/]: [Citizens] Enabling Citizens v2.0.13-SNAPSHOT (build 1130)
[15:29:17] [Server thread/INFO] [Minecraft/]: Creating file: config.yml
[15:29:18] [Server thread/ERROR] [Minecraft/]: [Citizens] v2.0.13-SNAPSHOT (build 1130) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling.
[15:29:18] [Server thread/INFO] [net.citizensnpcs.Citizens/]: [Citizens] Disabling Citizens v2.0.13-SNAPSHOT (build 1130)`

`[15:29:18] [Server thread/INFO] [me.blackvein.quests.Quests/]: [Quests] Enabling Quests v2.6.5-b104
[15:29:18] [Server thread/ERROR] [Minecraft/]: Error occurred while enabling Quests v2.6.5-b104 (Is it up to date?)
java.lang.NoClassDefFoundError: net/citizensnpcs/api/CitizensPlugin
	at me.blackvein.quests.Quests.linkOtherPlugins(Quests.java:400) ~[?:?]
	at me.blackvein.quests.Quests.onEnable(Quests.java:183) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316) ~[JavaPlugin.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368) [JavaPluginLoader.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410) [SimplePluginManager.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349) [CraftServer.class:git-Cauldron-MCPC-Plus-1.7.10-1.1236.06.212]
	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:500) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:474) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:434) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:329) [lt.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:620) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_45]`

**Comment by DNx5** [comment]
get the correct version of Citizens2
here: http://wiki.citizensnpcs.co/Versions

**Comment by DevinderFTW** [comment]
Is it the citizens-2.0.13-SNAPSHOT.jar?

**Comment by mcmonkey4eva** [comment]
You appear to be on MCPC/Cauldron 1.7.10, right?
That requires this specific build: https://dl.dropboxusercontent.com/u/6701575/citizens-2.0.13-1.7.10-Cauldron-B2.jar

**Comment by DevinderFTW** [comment]
Yes mcmonkey4eva and i just change this one to the one i have in the plugin's folder?

**Comment by mcmonkey4eva** [comment]
... Yes. Just swap your current citizens jar for this one in the plugins folder, as per usual.

**Comment by DevinderFTW** [comment]
Alright, thanks alot i will just test it now and i will get back in touch with any error!
