### ISSUE TITLE
Citizens plugin error on Paper 1.21.1 server

### ISSUE THREAD

**Issue by thisisaef** [CitizensDev/Citizens2#3168]
### `/version` output

```txt
This server is running Paper version 1.21.1-128-master@d348cb8 (2024-10-21T16:23:24Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
```

### `/version Citizens` output

```txt
Citizens version 2.0.36-SNAPSHOT (build 3607)
```

### Log file

https://paste.helpch.at/wumosefiqu.rb

### config.yml

https://paste.helpch.at/vuwibupiru.yaml

### saves.yml

https://paste.helpch.at/jufefeyide.yaml

### Profiler report

https://spark.lucko.me/mxA4aHCBLE

### Description

When attempting to enable the Citizens plugin (version 2.0.36-SNAPSHOT, build 3607) on a Paper 1.21.1 server, the plugin fails to load due to `NoClassDefFoundError` for `org.bukkit.craftbukkit.v1_21_R2.boss.CraftBossBar`. Additionally, there is an issue fetching NMS fields for `Armadillo.SCARE_DISTANCE_VERTICAL`.

**Expected Behavior**
The Citizens plugin should enable without errors, allowing NPC functionalities to work correctly on the Paper 1.21.1 server.

**Actual Behavior**
The server logs show `NoClassDefFoundError` related to `CraftBossBar`, indicating a potential NMS compatibility issue. The plugin does not fully enable, causing NPC-related features to be unavailable.

**Steps to Reproduce**
1. Set up a Paper 1.21.1 server.
2. Install Citizens plugin version 2.0.36-SNAPSHOT (build 3607).
3. Start the server.
4. Observe the error messages in the console during the startup.

**Additional Information**
Tried updating Citizens to the latest available version compatible with Minecraft 1.21.1.
Issue may be related to changes in NMS or internal PaperMC modifications.

**Comment by SNWCreations** [comment]
duplicate of #3164 . 1.21.1 is no longer supported. You can grab a older build supporting it but old builds are not supportable.

**Comment by thisisaef** [comment]
Okay, I understand
