### ISSUE TITLE
Crashing or Not Functional

### ISSUE THREAD

**Issue by Nupper** [CitizensDev/Citizens2#1774]
Crash when Making new npc or just dose not function

Error When loading
`Error occured while enabling Citizens (2.0.25-SNAPSHOT (build 1675)) hook.[m
[14:16:33] [Server thread/WARN]: java.lang.NullPointerException
[14:16:33] [Server thread/WARN]: 	at de.Keyle.MyPet.util.hooks.CitizensHook.onEnable(CitizensHook.java:58)
[14:16:33] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHook(PluginHookManager.java:115)
[14:16:33] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHooks(PluginHookManager.java:168)
[14:16:33] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:383)
[14:16:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[14:16:33] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332)
[14:16:33] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402)
[14:16:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:421)
[14:16:33] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:347)
[14:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:570)
[14:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:532)
[14:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:410)
[14:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:270)
[14:16:33] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:675)
[14:16:33] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)`
` Error occurred while disabling Citizens v2.0.25-SNAPSHOT (build 1675) (Is it up to date?)
java.lang.NullPointerException: null
	at net.citizensnpcs.Citizens.onDisable(Citizens.java:272) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:256) ~[craftbukkit.jar:git-Bukkit-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:356) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:421) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:414) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.disablePlugins(CraftServer.java:364) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.stop(MinecraftServer.java:611) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:728) [craftbukkit.jar:git-Bukkit-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
[23:58:46] [Server thread/INFO]: `

Craftbukkit Version: 1.13.2 RO.1 - Snapshot
Citizens version: 2.0.25-snapshot (build 1675)

**Comment by mergu** [comment]
Bukkit development was discontinued 5 years ago. You should be either using [Spigot](https://www.spigotmc.org/wiki/buildtools/) or [Paper](https://papermc.io/downloads). I personally recommend Paper for its easy setup. Once you swap to either of these, if you still have an issue please post a link to the full startup log

**Comment by Nupper** [comment]
the version works with craftbukkit 1.14

**Comment by mergu** [comment]
Bukkit is maintained **only as an internal backsupport tool** by the Spigot team. You should not be running your server on it.

**Comment by Nupper** [comment]
i will see about converting other plugins to Spigot and maps.

**Comment by mergu** [comment]
All Bukkit/Spigot plugins are fully compatible with Spigot and Paper

**Comment by Nupper** [comment]
thanks for that i hope to see improvements ^^

**Comment by Nupper** [comment]
`[00:22:46] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.25-SNAPSHOT (build 1675)
[00:22:46] [Server thread/ERROR]: Error occurred while enabling Citizens v2.0.25-SNAPSHOT (build 1675) (Is it up to date?)
java.lang.NoClassDefFoundError: net/minecraft/server/v1_13_R2/BlockPosition$PooledBlockPosition
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_151]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_151]
	at net.citizensnpcs.util.NMS.loadBridge(NMS.java:254) ~[?:?]
	at net.citizensnpcs.Citizens.onEnable(Citizens.java:291) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_13_R2.BlockPosition$PooledBlockPosition
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:85) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:80) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_151]
	... 15 more
[00:22:46] [Server thread/INFO]: [Sentinel] Enabling Sentinel v1.7.2 (build 200)
[00:22:46] [Server thread/INFO]: [Sentinel] Sentinel loading...
[00:22:46] [Server thread/ERROR]: Error occurred while enabling Sentinel v1.7.2 (build 200) (Is it up to date?)
java.lang.NullPointerException: null
	at org.mcmonkey.sentinel.SentinelPlugin.onEnable(SentinelPlugin.java:190) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254) ~[spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697) [spigot.jar:git-Spigot-518206a-a5b9c7b]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
"
`[m[0;31;1mError occured while enabling Citizens (2.0.25-SNAPSHOT (build 1675)) hook.[m
[00:22:55] [Server thread/WARN]: java.lang.NullPointerException
[00:22:55] [Server thread/WARN]: 	at de.Keyle.MyPet.util.hooks.CitizensHook.onEnable(CitizensHook.java:58)
[00:22:55] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHook(PluginHookManager.java:115)
[00:22:55] [Server thread/WARN]: 	at de.Keyle.MyPet.api.util.hooks.PluginHookManager.enableHooks(PluginHookManager.java:168)
[00:22:55] [Server thread/WARN]: 	at de.Keyle.MyPet.MyPetPlugin.onEnable(MyPetPlugin.java:383)
[00:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:254)
[00:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[00:22:55] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:403)
[00:22:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugin(CraftServer.java:434)
[00:22:55] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R2.CraftServer.enablePlugins(CraftServer.java:348)
[00:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.l(MinecraftServer.java:579)
[00:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:541)
[00:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:419)
[00:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.DedicatedServer.init(DedicatedServer.java:294)
[00:22:55] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:697)
[00:22:55] [Server thread/WARN]: 	at java.lang.Thread.run(Unknown Source)
`
This server is running CraftBukkit version git-Spigot-518206a-a5b9c7b (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT)
Citizens version: 2.0.25-snapshot (build 1675)

This is loaded spigot.
`

**Comment by mergu** [comment]
Use the links I have provided you. Do not download spigot off the internet.

**Comment by Nupper** [comment]
![image](https://user-images.githubusercontent.com/6026902/57576043-1e3c0880-744f-11e9-8409-07cac4f552f1.png)
Issue has been fixed due to buildtool thank you and my apologizes
