### ISSUE TITLE
Doesn't work with Spigot 1.8.7

### ISSUE THREAD

**Issue by OldTownMC** [CitizensDev/Citizens2#414]
Log: http://pastebin.com/ncJwtQB6

Using Snapshot 16.

**Comment by mcmonkey4eva** [comment]
Edit the version restrictor in your config.yml file.

**Comment by OldTownMC** [comment]
Do you mean:
advanced:
  check-minecraft-version: true

**Comment by PikachuEXE** [comment]
I changed `check-minecraft-version` to `false`, then it works.

**Comment by TheNovaCoreMC** [comment]
Hmm i try the 
check-minecraft-version to false
it doesnt work... maybe  we need a spigot version one

**Comment by TheNovaCoreMC** [comment]
[13:17:46] [Server thread/INFO]: [BattleKits] Disabling tag functionality as TagAPI is not installed.
[13:17:46] [Server thread/INFO]: [Citizens] Enabling Citizens v2.0.13-SNAPSHOT (build 1168)

**Comment by TheNovaCoreMC** [comment]
it says http://java.lang.NoClassDefFoundError

**Comment by mcmonkey4eva** [comment]
@TheNovaCoreMC You have the wrong version of Citizens. Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by TheNovaCoreMC** [comment]
Thank You.

**Comment by TheNovaCoreMC** [comment]
Wait Dont Close !

**Comment by TheNovaCoreMC** [comment]
Im not yet done

**Comment by TheNovaCoreMC** [comment]
what if I changed check-minecraft-version to false

**Comment by mcmonkey4eva** [comment]
No, you need to get the correct version of Citizens.

**Comment by TheNovaCoreMC** [comment]
hmm my version is Spigot/Bukkit 1.8.3 can you help me ?
and for what is Citizens API ?

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions just get the correct version off the list.

And C2 API is for programmers.

**Comment by TheNovaCoreMC** [comment]
hmmm it dint work i just download the 1.8.3
its  http://dev.bukkit.org/bukkit-plugins/citizens/files/49-2-0-14-alpha-1-for-mc-1-8-1/
doesnt work i also try the Build #1230 "citizens-2.0.15-SNAPSHOT"
doesnt work. i use spigot with bukkit 1.8.3

**Comment by TheNovaCoreMC** [comment]
[13:18:07 INFO]: /npc create [name] ((-b,u) --at (x:y:z:world) --type (type) --t
rait ('trait1, trait2...') --b (behaviours))
>npc create 1
[13:18:09 WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Pa
cket
[13:18:09 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(Ci
tizensNPCRegistry.java:92)
[13:18:09 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:47)
[13:18:09 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(Ci
tizensNPCRegistry.java:40)
[13:18:09 WARN]:        at net.citizensnpcs.commands.NPCCommands.create(NPCComma
nds.java:320)
[13:18:09 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native M
ethod)
[13:18:09 WARN]:        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown S
ource)
[13:18:09 WARN]:        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unkno
wn Source)
[13:18:09 WARN]:        at java.lang.reflect.Method.invoke(Unknown Source)
[13:18:09 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeMe
thod(CommandManager.java:154)
[13:18:09 WARN]:        at net.citizensnpcs.api.command.CommandManager.execute(C
ommandManager.java:90)
[13:18:09 WARN]:        at net.citizensnpcs.api.command.CommandManager.executeSa
fe(CommandManager.java:178)
[13:18:09 WARN]:        at net.citizensnpcs.Citizens.onCommand(Citizens.java:236
)
[13:18:09 WARN]:        at org.bukkit.command.PluginCommand.execute(PluginComman
d.java:44)
[13:18:09 WARN]:        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCo
mmandMap.java:141)
[13:18:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchCo
mmand(CraftServer.java:646)
[13:18:09 WARN]:        at org.bukkit.craftbukkit.v1_8_R2.CraftServer.dispatchSe
rverCommand(CraftServer.java:632)
[13:18:09 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.aN(Dedic
atedServer.java:405)
[13:18:09 WARN]:        at net.minecraft.server.v1_8_R2.DedicatedServer.A(Dedica
tedServer.java:369)
[13:18:09 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.z(Minecr
aftServer.java:651)
[13:18:09 WARN]:        at net.minecraft.server.v1_8_R2.MinecraftServer.run(Mine
craftServer.java:554)
[13:18:09 WARN]:        at java.lang.Thread.run(Unknown Source)
[13:18:09 WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.serv
er.v1_8_R1.Packet
[13:18:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:91)
[13:18:09 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.findClass(Pl
uginClassLoader.java:86)
[13:18:09 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[13:18:09 WARN]:        at java.lang.ClassLoader.loadClass(Unknown Source)
[13:18:09 WARN]:        ... 21 more
>

**Comment by TheNovaCoreMC** [comment]
Please Reply Fast Im Fixing Mah Server this time

**Comment by mcmonkey4eva** [comment]
That error was /not/ from build 1230, which is the one linked to you.

**Comment by Morphan1** [comment]
@TheNovaCoreMC You seem a little rushed. Perhaps you forgot to remove one version of the plugin from your folder? If you're on 1.8.3, then build 1230 is definitely what you want.

**Comment by TheNovaCoreMC** [comment]
okay ill go check it. dont close this ticket okay ?

**Comment by TheNovaCoreMC** [comment]
i finally got it thanks
i only download last time is the 13 and the 16 snapshots

**Comment by TheNovaCoreMC** [comment]
![313123123123123](https://cloud.githubusercontent.com/assets/12781581/8028599/e16ec79c-0de3-11e5-91d0-af9a679f8e19.png)

**Comment by TheNovaCoreMC** [comment]
Its finally working ! thanks @Morphan1

**Comment by TheNovaCoreMC** [comment]
![image](https://cloud.githubusercontent.com/assets/12781581/8028618/1760de26-0de4-11e5-975c-55233d5ca41c.png)
