### ISSUE TITLE
citizens dont working on 1.7.10

### ISSUE THREAD

**Issue by MKMethosPL** [CitizensDev/Citizens2#467]
i have message

[Citizens] v2.0.11-SNAPSHOT (build 1098) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling.

**Comment by Morphan1** [comment]
perhaps this linking does help message you have
http://wiki.citizensnpcs.co/Versions

**Comment by MKMethosPL** [comment]
sorry but : 

[Citizens] v2.0.13-SNAPSHOT (build 1130) is not compatible with Minecraft v1.7.10 - try upgrading or downgrading Citizens. Disabling. version 1.7.9 not working ( sorry im from poland ^^ )

**Comment by MKMethosPL** [comment]
thanks :)

**Comment by MKMethosPL** [comment]
whiiiiit when i add this plugin have that error : 

[23:46:01] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_7_R4.ReportedException: Ticking entity
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:717) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
Caused by: java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
	at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	... 4 more
[23:46:01] [Server thread/ERROR]: 	Cause of unexpected exception was
java.lang.NoSuchMethodError: net.minecraft.server.v1_7_R4.PacketPlayOutPlayerInfo.<init>(Ljava/lang/String;ZI)V
	at net.citizensnpcs.npc.entity.EntityHumanNPC.updatePackets(EntityHumanNPC.java:277) ~[?:?]
	at net.citizensnpcs.npc.entity.EntityHumanNPC.h(EntityHumanNPC.java:150) ~[?:?]
	at net.minecraft.server.v1_7_R4.World.entityJoinedWorld(World.java:1620) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.World.playerJoinedWorld(World.java:1595) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.World.tickEntities(World.java:1460) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.WorldServer.tickEntities(WorldServer.java:516) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.v(MinecraftServer.java:706) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.DedicatedServer.v(DedicatedServer.java:289) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.u(MinecraftServer.java:584) ~[mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.MinecraftServer.run(MinecraftServer.java:490) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
	at net.minecraft.server.v1_7_R4.ThreadServerApplication.run(SourceFile:628) [mc.jar:git-Spigot-1.7.9-R0.2-207-g03373bb]
[23:46:01] [Server thread/ERROR]: This crash report has been saved to: /home/e24598/pliki/./crash-reports/crash-2015-07-28_23.46.01-server.txt
[23:46:01] [Server thread/INFO]: Stopping server

**Comment by Morphan1** [comment]
You said you were using 1.7.10
You're using 1.7.9

**Comment by mcmonkey4eva** [comment]
http://wiki.citizensnpcs.co/Versions You need either v1166 or v1186

**Comment by MKMethosPL** [comment]
this is v1166 Error

**Comment by mcmonkey4eva** [comment]
Then run v1186

**Comment by MKMethosPL** [comment]
yes , you re speed :) i tested this is ok thanks
