### ISSUE TITLE
Not working on 1.7.5 Spigot Build 1386

### ISSUE THREAD

**Issue by Pr0Acid** [CitizensDev/Citizens2#527]
I am using spigot 1.7.5 build 1386 and i have tried all the version an still no luck, it keeps disabling itself saying this is not the right version for 1.7.8.. :/
http://wiki.citizensnpcs.co/Versions

I have tried all version on that list and on the bukkit page.

**Comment by Talamar1** [comment]
Well, says you should be using build 1114, can you paste the errors from the console?

**Comment by Pr0Acid** [comment]
i tried that build just now and this is the error it gives me now. 
[14:27:49] [Server thread/WARN]: java.lang.NoClassDefFoundError: Could not initialize class net.citizensnpcs.npc.ai.MCTargetStrategy
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.npc.ai.CitizensNavigator.<init>(CitizensNavigator.java:37)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPC.<init>(CitizensNPC.java:43)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:319)
[14:27:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:27:49] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[14:27:49] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[14:27:49] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Method.java:483)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
[14:27:49] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[14:27:49] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:27:49] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[14:27:49] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchCommand(CraftServer.java:719)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PlayerConnection.handleCommand(PlayerConnection.java:984)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:829)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:148)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.ServerConnection.c(ServerConnection.java:77)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:705)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:273)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:568)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:474)
[14:27:49] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)

**Comment by Pr0Acid** [comment]
The build number is not citizens build its the spigot build. I have tried 1115 and 1114 as well as the latest builds of citizens.

**Comment by Pr0Acid** [comment]
This is what it says when i use 1115:
[14:33:36] [Server thread/ERROR]: [Citizens] v2.0.13-SNAPSHOT (build 1115) is not compatible with Minecraft v1.7.8 - try upgrading or downgrading Citizens. Disabling.

**Comment by Talamar1** [comment]
1115 is for 1.7.8, so that won't work.

**Comment by Pr0Acid** [comment]
but the message says its not compatible with 1.7.8 so it assumes i have 1.7.8 no?

**Comment by Talamar1** [comment]
I think I will have to have @fullwall look at this.  1114 should be the working version for 1.7.5, but it looks like something isn't registering correctly.

**Comment by Pr0Acid** [comment]
Here are my server build info:
>version
[14:38:56 INFO]: This server is running CraftBukkit version git-Spigot-1386 (MC: 1.7.8) (Implementing API version 1.7.5-R0.1-SNAPSHOT)

I have tried almost every Citizens build on the page so far :P

**Comment by Pr0Acid** [comment]
There are no dependencies right?

**Comment by Talamar1** [comment]
Shouldn't be.

**Comment by Talamar1** [comment]
Wait, you aren't running 1.7.5, you are running 1.7.8.
Did you try:
http://ci.citizensnpcs.co/job/Citizens2/1116/

**Comment by Pr0Acid** [comment]
Yea i have tried all the versions around that area, Here is the error code for build 1116:
>[14:50:04] [Server thread/WARN]: java.lang.NoClassDefFoundError: net/minecraft/server/v1_7_R3/Packet
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:92)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:47)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:40)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.commands.NPCCommands.create(NPCCommands.java:319)
[14:50:04] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[14:50:04] [Server thread/WARN]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[14:50:04] [Server thread/WARN]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[14:50:04] [Server thread/WARN]: 	at java.lang.reflect.Method.invoke(Unknown Source)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeMethod(CommandManager.java:153)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.execute(CommandManager.java:90)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.api.command.CommandManager.executeSafe(CommandManager.java:177)
[14:50:04] [Server thread/WARN]: 	at net.citizensnpcs.Citizens.onCommand(Citizens.java:236)
[14:50:04] [Server thread/WARN]: 	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44)
[14:50:04] [Server thread/WARN]: 	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:180)
[14:50:04] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R2.CraftServer.dispatchCommand(CraftServer.java:719)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PlayerConnection.handleCommand(PlayerConnection.java:984)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PlayerConnection.a(PlayerConnection.java:829)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PacketPlayInChat.a(PacketPlayInChat.java:28)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.PacketPlayInChat.handle(PacketPlayInChat.java:65)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.NetworkManager.a(NetworkManager.java:148)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.ServerConnection.c(ServerConnection.java:77)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.v(MinecraftServer.java:705)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.DedicatedServer.v(DedicatedServer.java:273)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.u(MinecraftServer.java:568)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.MinecraftServer.run(MinecraftServer.java:474)
[14:50:04] [Server thread/WARN]: 	at net.minecraft.server.v1_7_R2.ThreadServerApplication.run(SourceFile:618)
[14:50:04] [Server thread/WARN]: Caused by: java.lang.ClassNotFoundException: net.minecraft.server.v1_7_R3.Packet
[14:50:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:67)
[14:50:04] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:62)
[14:50:04] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:50:04] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[14:50:04] [Server thread/WARN]: 	... 26 more

**Comment by mcmonkey4eva** [comment]
@Pr0Acid why not just update to latest server release and plugins?
