### ISSUE TITLE
Citizens /npc create doesn't work on my server - Running spigot 1.8.3

### ISSUE THREAD

**Issue by TrueGameMaster** [CitizensDev/Citizens2#407]
/npc create doesn't come up with created (name) like it is supposed to but in stead comes up with this error message saying: "Please report this error: [See console] java.lang.NoClassDefFoundError: net/minecraft/server/v1_8_R1/Packet" Can someone tell me what this is and try to fix it please? I am running Spigot 1.8.3.

**Comment by mcmonkey4eva** [comment]
Wrong version of Citizens for your Spigot version. Get the correct one here: http://wiki.citizensnpcs.co/Versions

**Comment by TrueGameMaster** [comment]
Thx for the info.

**Comment by TysterTG** [comment]
After that day...Taylor nevered updated the plugin...or get the correct version....and never got himself a pony....

**Comment by TrueGameMaster** [comment]
Oh wow tyler. -_- just wow
